services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MT%fm@SG1
    ports:
      - 1433:1433
    volumes:
      - db-data:/var/opt/mssql
        
volumes:
  db-data: